# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d528b97d064653f016ee7a21af89424970b1ae13d62001ae9b17066145ed7e1d9d6ab6da753b19e46e7c30b9e42965857219294c195b7f82811ac347733812ab

test:
  secret_key_base: 9c9181f1621d36a252322d1ce693b3a4e5fe836bee9bc63bdd4f53ad0ab270f19d4fd6125d5e612192db1b2a43b3eb5c8963ead544de4ee42ef7166478e1c372

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
